export class Customer {
    constructor(
        public Key?: string,
        public No?: string,
        public Name?: string,
        public Salesperson_Code?: string,
        public Country_Region_Code?: string,
        public Phone_No?: string,
        public Location_Market?: string,
        public Customer_Posting_Group?: string,
        public Gen_Bus_Posting_Group?: string,
        public VAT_Bus_Posting_Group?: string,
        public Customer_Price_Group?: string,
        public Customer_Disc_Group?: string,
        public Payment_Terms_Code?: string,
        public Reminder_Terms_Code?: string,
        public Fin_Charge_Terms_Code?: string,
        public Currency_Code?: string,
        public Language_Code?: string,
        public Search_Name?: string,
        public Credit_Limit_LCY?: number,
        public Blocked?: string,
        public Last_Date_Modified?: string,
        public Application_Method?: string,
        public Combine_Shipments?: number,
        public Reserve?: string,
        public Shipping_Advice?: string,
        public Shipping_Agent_Code?: string,
        public Base_Calendar_Code?: string,
        public Balance_LCY?: number,
        public Balance_Due_LCY?: number,
        public Sales_LCY?: number,
        
    ) {}
}
