export class Farmer {
  constructor(
    public Key?,
    public Application_No?,
    public Outrower_Name?,
    public Application_Date?,
    public National_ID_No?,
    public Huduma_No?,
    public KRA_PIN_No?,
    public Address?,
    public City?,
    public Phone_No?,
    public Email?,
    public Bank_Account_Code?,
    public Bank_Account_No?,
    public Bank_Account_Name?,
    public Total_Acres?,
    public Hectares?,
    public Route_Code?,
    public Route_Name?,
    public Buying_Centre_Code?,
    public Buying_Centre_Name?,
    public Land_Registration?,
    public Inspection_Date?,
    public Type_Of_Tea_Planted?,
    public GPS_Coordinates?,
    public Approval_Status?,
    public Created_On?,
    public Created_By?,
  ) {}
}
