export class Itemledgerentry {
    constructor(
        public Posting_Date? ,
        public Entry_Type? ,
        public Document_Type? ,
        public Document_No? ,
        public Source_No? ,
        public Vendor_Name? ,
        public Document_Line_No? ,
        public Item_No? ,
        public Variant_Code? ,
        public Description? ,
        public Return_Reason_Code? ,
        public Global_Dimension_1_Code? ,
        public Global_Dimension_2_Code? ,
        public Expiration_Date? ,
        public Serial_No? ,
        public Lot_No? ,
        public Location_Code? ,
        public Quantity? ,
        public Invoiced_Quantity? ,
        public Remaining_Quantity? ,
        public Shipped_Qty_Not_Returned? ,
        public Reserved_Quantity? ,
        public Qty_per_Unit_of_Measure? ,
        public Sales_Amount_Expected? ,
        public Sales_Amount_Actual? ,
        public Cost_Amount_Expected? ,
        public Cost_Amount_Actual? ,
        public Cost_Amount_Non_Invtbl? ,
        public Cost_Amount_Expected_ACY? ,
        public Cost_Amount_Actual_ACY? ,
        public Cost_Amount_Non_Invtbl_ACY? ,
        public Completely_Invoiced? ,
        public Open? ,
        public Drop_Shipment? ,
        public Assemble_to_Order? ,
        public Applied_Entry_to_Adjust? ,
        public Order_Type? ,
        public Order_No? ,
        public Order_Line_No? ,
        public Prod_Order_Comp_Line_No? ,
        public Entry_No? ,
        public Job_No? ,
        public Job_Task_No? ,
    ){}
}