export class Postedsalesinvoice {
    constructor(
        public Key?: string,
        public No?,
        public Sell_to_Customer_Name?,
        public Amount?,
        public Amount_Including_VAT?,
        public Remaining_Amount?,
        public Sell_to_Address?,
        public Sell_to_Address_2?,
        public Sell_to_Post_Code?,
        public Sell_to_City?,
        public Sell_to_Contact_No?,
        public Sell_to_Contact?,
        public Document_Date?,
        public Posting_Date?,
        public Due_Date?,
        public Document_Exchange_Status?,
        public Quote_No?,
        public Order_No?,
        public Pre_Assigned_No?,
        public External_Document_No?,
        public Salesperson_Code?,
        public Responsibility_Center?,
        public No_Printed?,
        public Cancelled?,
        public Corrective?,
        public Closed?,
        public GetWorkDescription?,
        public Currency_Code?,
        public Shipment_Date?,
        public Payment_Terms_Code?,
        public Payment_Method_Code?,
        public SelectedPayments?,
        public Shortcut_Dimension_1_Code?,
        public Shortcut_Dimension_2_Code?,
        public Payment_Discount_Percent?,
        public Pmt_Discount_Date?,
        public Direct_Debit_Mandate_ID?,
        public Location_Code?,
        public Shipment_Method_Code?,
        public Shipping_Agent_Code?,
        public Package_Tracking_No?,
        public Ship_to_Code?,
        public Ship_to_Name?,
        public Ship_to_Address?,
        public Ship_to_Address_2?,
        public Ship_to_Post_Code?,
        public Ship_to_City?,
        public Ship_to_Contact?,
        public Bill_to_Name?,
        public Bill_to_Address?,
        public Bill_to_Address_2?,
        public Bill_to_Post_Code?,
        public Bill_to_City?,
        public Bill_to_Contact_No?,
        public Bill_to_Contact?,
        public EU_3_Party_Trade?,
        public Transaction_Specification?,
        public Transport_Method?,
        public Exit_Point?,
        public Area?,
        public SalesInvLines?: { Posted_Sales_Invoice_Line: [
            {
                 Key?,
                 Type?,
                 No?,
                 Cross_Reference_No?,
                 IC_Partner_Code?,
                 Variant_Code?,
                 Description?,
                 Return_Reason_Code?,
                 Quantity?,
                 Unit_of_Measure_Code?,
                 Unit_of_Measure?,
                 Unit_Cost_LCY?,
                 Unit_Price?,
                 Line_Amount?,
                 Line_Discount_Percent?,
                 Line_Discount_Amount?,
                 Allow_Invoice_Disc?,
                 Job_No?,
                 Job_Task_No?,
                 Job_Contract_Entry_No?,
                 Appl_to_Item_Entry?,
                 Deferral_Code?,
                 Shortcut_Dimension_1_Code?,
                 Shortcut_Dimension_2_Code?,
                 Invoice_Discount_Amount?,
                 Total_Amount_Excl_VAT?,
                 Total_VAT_Amount?,
                 Total_Amount_Incl_VAT?,
            }
        ]}

    ) {}
}