export class Requisitionline {
    constructor(
        public Key?: string,
        public Document_No?: string,
        public Line_No?: string,
        public Item_No?: string ,
        public Variant_Code?: string ,
        public Planning_Flexibility?: string ,
        public Description?: string,
        public Unit?: string ,
        public Unit_Weight?: number ,
        public Pieces?: number ,
        public Transfer_from_Bin_Code?: string ,
        public Transfer_To_Bin_Code?: string,
        public Quantity?: number ,
        public Reserved_Quantity_Inbnd?: number ,
        public Reserved_Quantity_Shipped?: number ,
        public Reserved_Quantity_Outbnd?: number ,
        public Unit_of_Measure_Code?: string,
        public Unit_of_Measure?: string,
        public Qty_to_Ship?: number,
        public Quantity_Shipped?: number,
        public Qty_to_Receive?: number ,
        public Quantity_Received?: number,
        public Shipment_Date?: string,
        public Receipt_Date?: string,
        public Shipping_Agent_Code?: string,
        public Shipping_Agent_Service_Code?: string,
        public Shipping_Time?: string,
        public Outbound_Whse_Handling_Time?: string,
        public Inbound_Whse_Handling_Time?: string,
        public Appl_to_Item_Entry?: string,
        public Shortcut_Dimension_1_Code?: string,
        public Shortcut_Dimension_2_Code?: string,
        public ShortcutDimCode_x005B_3_x005D_?: string,
        public ShortcutDimCode_x005B_4_x005D_?: string,
        public ShortcutDimCode_x005B_5_x005D_?: string,
        public ShortcutDimCode_x005B_6_x005D_?: string,
        public ShortcutDimCode_x005B_7_x005D_?: string,
        public ShortcutDimCode_x005B_8_x005D_?: string,

    ) {}
}